POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hbHV1a2FpIiwiaWQiOiI2M2M1ZTE4MTI5YzAyMjc4YWViNDMwZDEiLCJpYXQiOjE2NzQwMDM5NDl9.DLRAGN7NWsshf55RGPfuoWtJNRyMVZvcVgXBFjzlilg

{
  "content": "single page app",
  "important": true
}
